/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni/jni.h"
/* Header for class test_MyJniApi */

#ifndef _Included_test_MyJniApi
#define _Included_test_MyJniApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_MyJniApi
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_test_MyJniApi_sum
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
